apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: allrounder
spec:
  ingressClassName: traefik
  rules:
    - host: api.placeholder.invalid
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  name: http
    - host: app.placeholder.invalid
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui
                port:
                  name: http
