"""Simple invoice PDF: one page carrying every field the bills lane extracts.

Draws vendor name, invoice number, total and due date, plus an optional
remittance line, so a demo or pilot vendor email can carry a realistic
attachment. Layout only, no network calls, no state.

Usage (repo root):
    python scripts/msp-invoice.py --vendor "Acme Power Pty Ltd" --number 4417 \
        --amount 220.00 --due 2026-10-15 --to "Northside Dental" \
        --bsb 012-345 --account 12345678 --account-name "Acme Power Pty Ltd"
"""

from __future__ import annotations

import argparse
import sys
from datetime import date, timedelta
from decimal import Decimal, InvalidOperation
from io import BytesIO
from pathlib import Path
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.enums import TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

INK = colors.HexColor("#111827")
MUTED = colors.HexColor("#6b7280")
LINE = colors.HexColor("#d1d5db")
PAPER = colors.HexColor("#f9fafb")

TITLE = ParagraphStyle(
    "InvoiceTitle", fontName="Helvetica-Bold", fontSize=18, leading=22, textColor=INK
)
TAG = ParagraphStyle(
    "InvoiceTag",
    fontName="Helvetica-Bold",
    fontSize=12,
    leading=22,
    textColor=MUTED,
    alignment=TA_RIGHT,
)
LABEL = ParagraphStyle(
    "InvoiceLabel", fontName="Helvetica", fontSize=9, leading=12, textColor=MUTED
)
BODY = ParagraphStyle(
    "InvoiceBody", fontName="Helvetica", fontSize=10.5, leading=15, textColor=INK
)
VALUE = ParagraphStyle(
    "InvoiceValue", fontName="Helvetica-Bold", fontSize=10.5, leading=15, textColor=INK
)
TOTAL = ParagraphStyle(
    "InvoiceTotal", fontName="Helvetica-Bold", fontSize=14, leading=18, textColor=INK
)
NOTE = ParagraphStyle(
    "InvoiceNote", fontName="Helvetica", fontSize=8, leading=11, textColor=MUTED
)


def build_pdf(
    *,
    vendor: str,
    number: str,
    amount: Decimal,
    issued: date,
    due: date,
    billed_to: str,
    bsb: str,
    account: str,
    account_name: str,
) -> bytes:
    """One A4 page; the same number, due date and total the lane extracts."""

    buffer = BytesIO()
    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=22 * mm,
        bottomMargin=22 * mm,
        title=f"Invoice {number}",
        author=vendor,
    )
    header = Table(
        [[Paragraph(escape(vendor), TITLE), Paragraph("INVOICE", TAG)]],
        colWidths=[110 * mm, 50 * mm],
    )
    meta = Table(
        [
            [Paragraph("Invoice number", LABEL), Paragraph(escape(number), VALUE)],
            [Paragraph("Issued", LABEL), Paragraph(issued.isoformat(), VALUE)],
            [Paragraph("Due", LABEL), Paragraph(due.isoformat(), VALUE)],
        ],
        colWidths=[45 * mm, 60 * mm],
        hAlign="LEFT",
    )
    billed = Paragraph(f"<b>Billed to</b><br/>{escape(billed_to)}", BODY)
    amounts = Table(
        [[Paragraph("Total (incl GST)", LABEL), Paragraph(f"${amount:,.2f}", TOTAL)]],
        colWidths=[110 * mm, 50 * mm],
    )
    amounts.setStyle(
        TableStyle(
            [
                ("BOX", (0, 0), (-1, -1), 0.6, LINE),
                ("BACKGROUND", (0, 0), (-1, -1), PAPER),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("ALIGN", (1, 0), (1, 0), "RIGHT"),
            ]
        )
    )
    story: list[object] = [
        header,
        Spacer(1, 12 * mm),
        meta,
        Spacer(1, 12 * mm),
        billed,
        Spacer(1, 10 * mm),
        amounts,
    ]
    if account:
        parts = [f"account {account}"]
        if bsb:
            parts.insert(0, f"BSB {bsb}")
        if account_name:
            parts.append(account_name)
        story += [Spacer(1, 10 * mm), Paragraph("Remittance: " + ", ".join(parts), BODY)]
    story += [
        Spacer(1, 16 * mm),
        Paragraph(
            "Sample document generated by scripts/msp-invoice.py for the bills "
            "lane demo. Not a tax invoice.",
            NOTE,
        ),
    ]
    document.build(story)
    return buffer.getvalue()


def main() -> int:
    parser = argparse.ArgumentParser(description="Write a one page invoice PDF.")
    parser.add_argument("--vendor", required=True, help="vendor or business name")
    parser.add_argument("--number", required=True, help="invoice number, e.g. 4417")
    parser.add_argument("--amount", required=True, help="total including GST, e.g. 220.00")
    parser.add_argument(
        "--due", default="", help="due date as YYYY-MM-DD (default: today plus 30 days)"
    )
    parser.add_argument("--to", dest="billed_to", default="Demo client", help="billed-to name")
    parser.add_argument("--bsb", default="", help="remittance BSB")
    parser.add_argument("--account", default="", help="remittance account number")
    parser.add_argument("--account-name", default="", help="remittance account name")
    parser.add_argument(
        "--out",
        default="",
        help="output path (default: tmp/invoices/invoice-<number>.pdf)",
    )
    args = parser.parse_args()

    vendor = args.vendor.strip()
    number = args.number.strip()
    billed_to = args.billed_to.strip() or "Demo client"
    bsb = args.bsb.strip()
    account = args.account.strip()
    account_name = args.account_name.strip()
    if vendor == "" or number == "":
        print("vendor and number must not be empty", file=sys.stderr)
        return 1
    if len(number) > 60:
        print("invoice number looks wrong: max 60 characters", file=sys.stderr)
        return 1
    try:
        amount = Decimal(args.amount.replace("$", "").replace(",", "")).quantize(
            Decimal("0.01")
        )
    except InvalidOperation:
        print(f"amount looks wrong: {args.amount!r}", file=sys.stderr)
        return 1
    if amount <= 0:
        print("amount looks wrong: must be positive", file=sys.stderr)
        return 1
    issued = date.today()
    due_raw = args.due.strip()
    if due_raw != "":
        try:
            due = date.fromisoformat(due_raw)
        except ValueError:
            print(f"due date looks wrong: {args.due!r}, expected YYYY-MM-DD", file=sys.stderr)
            return 1
    else:
        due = issued + timedelta(days=30)

    out_raw = args.out.strip()
    out = (
        Path(out_raw)
        if out_raw != ""
        else Path("tmp") / "invoices" / f"invoice-{number}.pdf"
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(
        build_pdf(
            vendor=vendor,
            number=number,
            amount=amount,
            issued=issued,
            due=due,
            billed_to=billed_to,
            bsb=bsb,
            account=account,
            account_name=account_name,
        )
    )
    print(f"wrote {out}")
    print("use it:")
    print("  attach it to a vendor email, then forward that email into the lane")
    print("  python scripts/msp-bill-demo.py --vendor <ref> --token $MSP_TOKEN")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
